/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CustomersAddModal: typeof import('./src/components/customers/CustomersAddModal.vue')['default']
    CustomersDeleteModal: typeof import('./src/components/customers/CustomersDeleteModal.vue')['default']
    HomeChart: typeof import('./src/components/home/HomeChart.vue')['default']
    HomeDateRangePicker: typeof import('./src/components/home/HomeDateRangePicker.vue')['default']
    HomePeriodSelect: typeof import('./src/components/home/HomePeriodSelect.vue')['default']
    HomeSales: typeof import('./src/components/home/HomeSales.vue')['default']
    HomeStats: typeof import('./src/components/home/HomeStats.vue')['default']
    HomeTopGames: typeof import('./src/components/home/HomeTopGames.vue')['default']
    InboxList: typeof import('./src/components/inbox/InboxList.vue')['default']
    InboxMail: typeof import('./src/components/inbox/InboxMail.vue')['default']
    NotificationsSlideover: typeof import('./src/components/NotificationsSlideover.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsMembersList: typeof import('./src/components/settings/SettingsMembersList.vue')['default']
    TeamsMenu: typeof import('./src/components/TeamsMenu.vue')['default']
    UAlert: typeof import('./../node_modules/.bun/@nuxt+ui@4.0.1+667948e7d4d8a20f/node_modules/@nuxt/ui/dist/runtime/components/Alert.vue')['default']
    UApp: typeof import('./../node_modules/.bun/@nuxt+ui@4.0.1+667948e7d4d8a20f/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UAuthForm: typeof import('./../node_modules/.bun/@nuxt+ui@4.0.1+667948e7d4d8a20f/node_modules/@nuxt/ui/dist/runtime/components/AuthForm.vue')['default']
    UBadge: typeof import('./../node_modules/.bun/@nuxt+ui@4.0.1+667948e7d4d8a20f/node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./../node_modules/.bun/@nuxt+ui@4.0.1+667948e7d4d8a20f/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCalendar: typeof import('./../node_modules/.bun/@nuxt+ui@4.0.1+667948e7d4d8a20f/node_modules/@nuxt/ui/dist/runtime/components/Calendar.vue')['default']
    UCard: typeof import('./../node_modules/.bun/@nuxt+ui@4.0.1+667948e7d4d8a20f/node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UChip: typeof import('./../node_modules/.bun/@nuxt+ui@4.0.1+667948e7d4d8a20f/node_modules/@nuxt/ui/dist/runtime/components/Chip.vue')['default']
    UDashboardNavbar: typeof import('./../node_modules/.bun/@nuxt+ui@4.0.1+667948e7d4d8a20f/node_modules/@nuxt/ui/dist/runtime/components/DashboardNavbar.vue')['default']
    UDashboardPanel: typeof import('./../node_modules/.bun/@nuxt+ui@4.0.1+667948e7d4d8a20f/node_modules/@nuxt/ui/dist/runtime/components/DashboardPanel.vue')['default']
    UDashboardSidebarCollapse: typeof import('./../node_modules/.bun/@nuxt+ui@4.0.1+667948e7d4d8a20f/node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebarCollapse.vue')['default']
    UDashboardToolbar: typeof import('./../node_modules/.bun/@nuxt+ui@4.0.1+667948e7d4d8a20f/node_modules/@nuxt/ui/dist/runtime/components/DashboardToolbar.vue')['default']
    UDropdownMenu: typeof import('./../node_modules/.bun/@nuxt+ui@4.0.1+667948e7d4d8a20f/node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue')['default']
    UIcon: typeof import('./../node_modules/.bun/@nuxt+ui@4.0.1+667948e7d4d8a20f/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    ULink: typeof import('./../node_modules/.bun/@nuxt+ui@4.0.1+667948e7d4d8a20f/node_modules/@nuxt/ui/dist/runtime/vue/components/Link.vue')['default']
    UPageCard: typeof import('./../node_modules/.bun/@nuxt+ui@4.0.1+667948e7d4d8a20f/node_modules/@nuxt/ui/dist/runtime/components/PageCard.vue')['default']
    UPageGrid: typeof import('./../node_modules/.bun/@nuxt+ui@4.0.1+667948e7d4d8a20f/node_modules/@nuxt/ui/dist/runtime/components/PageGrid.vue')['default']
    UPopover: typeof import('./../node_modules/.bun/@nuxt+ui@4.0.1+667948e7d4d8a20f/node_modules/@nuxt/ui/dist/runtime/components/Popover.vue')['default']
    USelect: typeof import('./../node_modules/.bun/@nuxt+ui@4.0.1+667948e7d4d8a20f/node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    UserMenu: typeof import('./src/components/UserMenu.vue')['default']
    USkeleton: typeof import('./../node_modules/.bun/@nuxt+ui@4.0.1+667948e7d4d8a20f/node_modules/@nuxt/ui/dist/runtime/components/Skeleton.vue')['default']
    UTable: typeof import('./../node_modules/.bun/@nuxt+ui@4.0.1+667948e7d4d8a20f/node_modules/@nuxt/ui/dist/runtime/components/Table.vue')['default']
    UTooltip: typeof import('./../node_modules/.bun/@nuxt+ui@4.0.1+667948e7d4d8a20f/node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue')['default']
  }
}
